### ISSUE TITLE
Task: W3C Compliant DID Doc Implementation

### ISSUE THREAD

**Issue by dbluhm** [rd-dlab/aries-cloudagent-python#21]
Implement a W3C DID Spec compliant DID Doc implementation for use in DID Resolvers.

The implementation should:
- support deserializing from and serializing to the DID Doc Data Model defined in the DID Spec
- support construction from native python objects (i.e. `__init__` accepts a list of `VerificationMethod` objects, a list of `Service` objects, etc.)
- have helpers or shortcuts for accessing the parts relevant to DID Communication (i.e. services of type `did-communication` or `IndyAgent` and the keys inside of those services)
- use some form of validation using Marshmallow or something else
  - Marshmallow is preferable to other solutions but lacks polymorphism which is needed to fully express the DID Doc Data Model. Specifically, this is needed for fields that can be a `verificationMethod` map OR a DID URL string, etc.. This can be worked around with custom fields or extending Schema but this may not be a good approach.
- include objects representing the various pieces of DID Documents but especially for verification methods and services
  - Not all verification methods will be supported by ACA-Py at this time but our object representation should help us identify whether the verification method (usually a public key) in question is one we support.

### References
- [DID Spec](https://w3c.github.io/did-core/)
- [ACA-Py's current DID Doc representation](https://github.com/hyperledger/aries-cloudagent-python/blob/4f873d942b57959d31880fd2e287d468d82de411/aries_cloudagent/connections/models/diddoc/diddoc.py#L33)
  - Deficient because of hard coded `did:sov` for all DID values and Doc references and out of date with DID Spec
- [Preliminary stopgap DID Doc implementation](https://github.com/rd-dlab/aries-cloudagent-python/blob/feature/did-resolver/aries_cloudagent/resolver/diddoc.py#L37)
  - Deficient because constructing a Doc in code is painful and error prone, accessing members is driven through dictionary access, no objects for service, verification method, etc.

### Tasks

- [ ] DID Doc class
- [ ] Verification method class
- [ ] Service class
- [ ] Tests demonstrating functionality
  - [ ] serializing
  - [ ] deserializing
  - [ ] constructing from code
  - [ ] accessing DID Comm related services
  - [ ] accessing specific verification methods
  - [ ] rejects poorly formatted DID Docs

Story #8
